# Package Build Configuration 
name: PCK.AUTOMIC_MSSQL

source: ae

# binary object resource mapping will be defined here
binaries:
  - object: RESOURCES/PCK.AUTOMIC_MSSQL.PRV.CUSTOM_TYPES
    timestamp: disabled
    resources: 
    - name: DEPLOYMENTTARGET#MSSQL#1
      type: TEXT
      path: ara/types/deploymenttarget/MSSQL.xml
      version: 6.0
    - name: COMPONENT#MSSQL#2
      type: TEXT
      path: ara/types/component/MSSQL.xml
      version: 6.0